CREATE TABLE TB_USERS (
    ID SERIAL NOT NULL PRIMARY KEY,
    NAME VARCHAR(255),
    EMAIL VARCHAR(255) UNIQUE,
    PASSWORD VARCHAR(255),
    STATUS VARCHAR(100),
    CREATE_DATE_TIME TIMESTAMP,
    UPDATE_DATE_TIME TIMESTAMP
);