ALTER TABLE TB_USERS ADD CREATE_USER INTEGER;
ALTER TABLE TB_USERS ADD UPDATE_USER INTEGER;
ALTER TABLE TB_USERS ADD CONSTRAINT TB_USERS_CREATE_USER_FK FOREIGN KEY (CREATE_USER) REFERENCES TB_USERS(ID);
ALTER TABLE TB_USERS ADD CONSTRAINT TB_USERS_UPDATE_USER_FK FOREIGN KEY (UPDATE_USER) REFERENCES TB_USERS(ID);