CREATE TABLE TB_CATEGORIES (
    ID SERIAL NOT NULL PRIMARY KEY,
    NAME VARCHAR(255),
    STATUS VARCHAR(100),
    CREATE_DATE_TIME TIMESTAMP,
    UPDATE_DATE_TIME TIMESTAMP,
    CREATE_USER INTEGER,
    UPDATE_USER INTEGER
);