CREATE TABLE TB_POSTS (
    ID SERIAL NOT NULL PRIMARY KEY,
    PATH VARCHAR(255),
    CATEGORY INTEGER,
    TITLE VARCHAR(255),
    BODY TEXT,

    STATUS VARCHAR(100),
    CREATE_DATE_TIME TIMESTAMP,
    UPDATE_DATE_TIME TIMESTAMP,
    CREATE_USER INTEGER,
    UPDATE_USER INTEGER,

    CONSTRAINT TB_POSTS_CREATE_USER_FK FOREIGN KEY (CREATE_USER) REFERENCES TB_USERS(ID),
    CONSTRAINT TB_POSTS_UPDATE_USER_FK FOREIGN KEY (UPDATE_USER) REFERENCES TB_USERS(ID),
    CONSTRAINT TB_POSTS_CATEGORY_FK FOREIGN KEY (CATEGORY) REFERENCES TB_CATEGORIES(ID)
);